apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-backend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: admin-backend
  template:
    metadata:
      labels:
        app: admin-backend
    spec:
      containers:
      - image: docker.io/raityupiyo/cs-admin-backend:40dfa65d1f826d95a669a6d766af0b1d55a9d4d9 
        name: admin-backend
        ports:
        - containerPort: 9000