apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-backend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: end-backend
  template:
    metadata:
      labels:
        app: end-backend
    spec:
      containers:
      - image: docker.io/raityupiyo/cs-end-backend:f962f4c459e09d3cad6a295505d8cf6ea50195a9
        name: end-backend
        ports:
        - containerPort: 9000