apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: end-frontend
  template:
    metadata:
      labels:
        app: end-frontend
    spec:
      containers:
      - image: docker.io/raityupiyo/cs-end-frontend:latest 
        name: end-frontend
        ports:
        - containerPort: 80