apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: end-frontend
  template:
    metadata:
      labels:
        app: end-frontend
    spec:
      containers:
        - image: docker.io/raityupiyo/cs-end-frontend:17
          name: end-frontend
          ports:
            - containerPort: 3000
