apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-backend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: end-backend
  template:
    metadata:
      labels:
        app: end-backend
    spec:
      containers:
      - image: docker.io/raityupiyo/cs-end-backend:faed35323e661c6bfd5761688685febe0b215c43
        name: end-backend
        ports:
        - containerPort: 9000