apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: end-frontend
  template:
    metadata:
      labels:
        app: end-frontend
    spec:
      containers:
      - image: docker.io/raityupiyo/cs-end-frontend:63fbfcfa29d2e8b698b001a077535f1fb55254f9 
        name: end-frontend
        ports:
        - containerPort: 3000